server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://db:3307/mall_db?useSSL=false&serverTimezone=UTC&connectTimeout=30000&allowPublicKeyRetrieval=true
    username: ezmall
    password: ezmallpassword
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

  data:
    redis:
      host: redis
      port: 6379
